// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TspuWebPortal.ORM;

#nullable disable

namespace TspuWebPortal.Migrations
{
    [DbContext(typeof(TspuDbContext))]
    [Migration("20220419121538_UnitAddLinks")]
    partial class UnitAddLinks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TspuWebPortal.Model.CableData", b =>
                {
                    b.Property<int>("CableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CableId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<int>("DetailChangeId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityModelId")
                        .HasColumnType("integer");

                    b.Property<int>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CableId");

                    b.HasIndex("DetailChangeId");

                    b.HasIndex("EntityModelId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Cables");
                });

            modelBuilder.Entity("TspuWebPortal.Model.CardData", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardSlotInChassis")
                        .HasColumnType("text");

                    b.Property<string>("CardStatus")
                        .HasColumnType("text");

                    b.Property<int?>("ChassisId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("text");

                    b.Property<int?>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<int?>("DetailChangeId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntityModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("InventoryNumber")
                        .HasColumnType("text");

                    b.Property<bool?>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionInUpperEntity")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("SnType")
                        .HasColumnType("text");

                    b.HasKey("CardId");

                    b.HasIndex("ChassisId");

                    b.HasIndex("DetailChangeId");

                    b.HasIndex("EntityModelId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChangeApplicationData", b =>
                {
                    b.Property<int>("DetailChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetailChangeId"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CompleteChangeDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<int>("JiraApplicationId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestCompletionId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestCreationId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsiblePerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnNewDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnOldDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DetailChangeId");

                    b.HasIndex("RequestCompletionId")
                        .IsUnique();

                    b.HasIndex("RequestCreationId")
                        .IsUnique();

                    b.ToTable("DetailChange");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChassisData", b =>
                {
                    b.Property<int>("ChassisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChassisId"));

                    b.Property<string>("ChassisStatus")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("text");

                    b.Property<int?>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<int?>("DetailChangeId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntityModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Hostname")
                        .HasColumnType("text");

                    b.Property<int?>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("InventoryNumber")
                        .HasColumnType("text");

                    b.Property<bool?>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionInUpperEntity")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("SnType")
                        .HasColumnType("text");

                    b.HasKey("ChassisId");

                    b.HasIndex("DetailChangeId");

                    b.HasIndex("EntityModelId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Chassis");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DcData", b =>
                {
                    b.Property<int>("DataCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DataCenterId"));

                    b.Property<string>("DataCenterAddress")
                        .HasColumnType("text");

                    b.Property<string>("DataCenterName")
                        .HasColumnType("text");

                    b.HasKey("DataCenterId");

                    b.ToTable("DataCenters");
                });

            modelBuilder.Entity("TspuWebPortal.Model.EntityModelData", b =>
                {
                    b.Property<int>("EntityModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityModelId"));

                    b.Property<int>("MaximalPower")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NominalPower")
                        .HasColumnType("integer");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EntityModelId");

                    b.ToTable("EntityModel");
                });

            modelBuilder.Entity("TspuWebPortal.Model.FileData", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileId"));

                    b.Property<string>("FileCategory")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAppliedToTable")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastChangeDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("UploadDate")
                        .HasColumnType("date");

                    b.HasKey("FileId");

                    b.ToTable("FileData");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialDetailRecordData", b =>
                {
                    b.Property<int>("InitialDetailRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InitialDetailRecordId"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("DetailOfficialName")
                        .HasColumnType("text");

                    b.Property<int?>("DetailOrigin")
                        .HasColumnType("integer");

                    b.Property<int?>("EntityModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("InitialDetailTableId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsSplittable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSuccessfullyUploaded")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int?>("OperationId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsiblePerson")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.HasKey("InitialDetailRecordId");

                    b.HasIndex("EntityModelId");

                    b.HasIndex("InitialDetailTableId");

                    b.HasIndex("OperationId");

                    b.ToTable("DetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialDetailTableData", b =>
                {
                    b.Property<int>("InitialDetailTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InitialDetailTableId"));

                    b.Property<int?>("FileId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("RegisterDate")
                        .HasColumnType("date");

                    b.HasKey("InitialDetailTableId");

                    b.HasIndex("FileId");

                    b.ToTable("DetailTable");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialMaterialRecordData", b =>
                {
                    b.Property<int>("InitialMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InitialMaterialId"));

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InitialMaterialTableId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialOfficialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("InitialMaterialId");

                    b.HasIndex("InitialMaterialTableId");

                    b.HasIndex("OperationId");

                    b.ToTable("MaterialRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialMaterialTableData", b =>
                {
                    b.Property<int>("InitialMaterialTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InitialMaterialTableId"));

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int?>("TableFileFileId")
                        .HasColumnType("integer");

                    b.HasKey("InitialMaterialTableId");

                    b.HasIndex("TableFileFileId");

                    b.ToTable("MaterialTable");
                });

            modelBuilder.Entity("TspuWebPortal.Model.LicenseData", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LicenseId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<int>("EntityModelId")
                        .HasColumnType("integer");

                    b.Property<int>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LicenseId");

                    b.HasIndex("EntityModelId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("TspuWebPortal.Model.LinkData", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkId"));

                    b.Property<int>("CableId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<int>("ModuleAId")
                        .HasColumnType("integer");

                    b.Property<int>("ModuleBId")
                        .HasColumnType("integer");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.Property<string>("RdLinkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualPortA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualPortB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LinkId");

                    b.HasIndex("CableId");

                    b.HasIndex("ModuleAId")
                        .IsUnique();

                    b.HasIndex("ModuleBId")
                        .IsUnique();

                    b.ToTable("Links");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleAData", b =>
                {
                    b.Property<int>("ModuleAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleAId"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.HasKey("ModuleAId");

                    b.HasIndex("ModuleId")
                        .IsUnique();

                    b.ToTable("ModulesA");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleBData", b =>
                {
                    b.Property<int>("ModuleBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleBId"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.HasKey("ModuleBId");

                    b.HasIndex("ModuleId")
                        .IsUnique();

                    b.ToTable("ModulesB");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleData", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<int?>("CardId")
                        .HasColumnType("integer");

                    b.Property<string>("CardSlotInChassisOrCard")
                        .HasColumnType("text");

                    b.Property<int?>("ChassisId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("text");

                    b.Property<int?>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<int?>("DetailChangeId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntityModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("InventoryNumber")
                        .HasColumnType("text");

                    b.Property<bool?>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<string>("ModuleStatus")
                        .HasColumnType("text");

                    b.Property<string>("PositionInUpperEntity")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ServeroMesto")
                        .HasColumnType("integer");

                    b.Property<string>("SnType")
                        .HasColumnType("text");

                    b.HasKey("ModuleId");

                    b.HasIndex("CardId");

                    b.HasIndex("ChassisId");

                    b.HasIndex("DetailChangeId");

                    b.HasIndex("EntityModelId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("TspuWebPortal.Model.OperationData", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("OperationDate")
                        .HasColumnType("date");

                    b.Property<string>("OperationType")
                        .HasColumnType("text");

                    b.Property<int?>("UserListAccountId")
                        .HasColumnType("integer");

                    b.HasKey("OperationId");

                    b.HasIndex("UserListAccountId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RackData", b =>
                {
                    b.Property<int>("RackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RackId"));

                    b.Property<int?>("FreeServerSlotsQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("InstallationYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<int?>("RackHeight")
                        .HasColumnType("integer");

                    b.Property<string>("RackNameAsbi")
                        .HasColumnType("text");

                    b.Property<string>("RackNameDataCenter")
                        .HasColumnType("text");

                    b.Property<string>("RackType")
                        .HasColumnType("text");

                    b.Property<int?>("RowId")
                        .HasColumnType("integer");

                    b.HasKey("RackId");

                    b.HasIndex("RowId");

                    b.ToTable("Racks");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCompletionData", b =>
                {
                    b.Property<int>("RequestCompletionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestCompletionId"));

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.HasKey("RequestCompletionId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("CompletionRequests");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCreationData", b =>
                {
                    b.Property<int>("RequestCreationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestCreationId"));

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.HasKey("RequestCreationId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("CreationRequests");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RoomData", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("DataCenterId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomCoordinates")
                        .HasColumnType("text");

                    b.Property<string>("RoomName")
                        .HasColumnType("text");

                    b.HasKey("RoomId");

                    b.HasIndex("DataCenterId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RowData", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("RowNameAsbi")
                        .HasColumnType("text");

                    b.Property<string>("RowNameDataCenter")
                        .HasColumnType("text");

                    b.HasKey("RowId");

                    b.HasIndex("RoomId");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ServerLinkData", b =>
                {
                    b.Property<int>("ServerLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerLinkId"));

                    b.Property<int>("ServerSlotId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServerSlotsServerSlotId")
                        .HasColumnType("integer");

                    b.Property<int>("ServerTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ServerLinkId");

                    b.HasIndex("ServerSlotsServerSlotId");

                    b.ToTable("ServerLinks");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ServerSlotData", b =>
                {
                    b.Property<int>("ServerSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerSlotId"));

                    b.Property<string>("SlotIndex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("ServerSlotId");

                    b.ToTable("ServerSlots");
                });

            modelBuilder.Entity("TspuWebPortal.Model.SiteData", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("FederalDistrict")
                        .HasColumnType("text");

                    b.Property<string>("IsInProject")
                        .HasColumnType("text");

                    b.Property<string>("Links")
                        .HasColumnType("text");

                    b.Property<string>("MaintainanceStatus")
                        .HasColumnType("text");

                    b.Property<string>("Oper")
                        .HasColumnType("text");

                    b.Property<string>("PipelineStage")
                        .HasColumnType("text");

                    b.Property<int?>("RegionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SiteType")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("TspuWebPortal.Model.UnitData", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<int?>("ChassisId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsFront")
                        .HasColumnType("boolean");

                    b.Property<int?>("RackId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServerSlotId")
                        .HasColumnType("integer");

                    b.Property<int?>("UnitInRack")
                        .HasColumnType("integer");

                    b.HasKey("UnitId");

                    b.HasIndex("ChassisId");

                    b.HasIndex("RackId");

                    b.HasIndex("ServerSlotId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("TspuWebPortal.Model.UserListData", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("TspuWebPortal.Model.CableData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ChangeApplicationData", "DetailChange")
                        .WithMany("Cables")
                        .HasForeignKey("DetailChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.EntityModelData", "EntityModel")
                        .WithMany("Cables")
                        .HasForeignKey("EntityModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.InitialDetailRecordData", "InitialDetailRecord")
                        .WithMany("Cables")
                        .HasForeignKey("InitialDetailRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailChange");

                    b.Navigation("EntityModel");

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.CardData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ChassisData", "Chassis")
                        .WithMany("Cards")
                        .HasForeignKey("ChassisId");

                    b.HasOne("TspuWebPortal.Model.ChangeApplicationData", "DetailChange")
                        .WithMany("Cards")
                        .HasForeignKey("DetailChangeId");

                    b.HasOne("TspuWebPortal.Model.EntityModelData", "EntityModel")
                        .WithMany("Cards")
                        .HasForeignKey("EntityModelId");

                    b.HasOne("TspuWebPortal.Model.InitialDetailRecordData", "InitialDetailRecord")
                        .WithMany("Card")
                        .HasForeignKey("InitialDetailRecordId");

                    b.Navigation("Chassis");

                    b.Navigation("DetailChange");

                    b.Navigation("EntityModel");

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChangeApplicationData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.RequestCompletionData", "RequestCompletion")
                        .WithOne("ChangeApplication")
                        .HasForeignKey("TspuWebPortal.Model.ChangeApplicationData", "RequestCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.RequestCreationData", "RequestCreation")
                        .WithOne("ChangeApplication")
                        .HasForeignKey("TspuWebPortal.Model.ChangeApplicationData", "RequestCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestCompletion");

                    b.Navigation("RequestCreation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChassisData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ChangeApplicationData", "DetailChange")
                        .WithMany("Chassis")
                        .HasForeignKey("DetailChangeId");

                    b.HasOne("TspuWebPortal.Model.EntityModelData", "EntityModel")
                        .WithMany("Chassis")
                        .HasForeignKey("EntityModelId");

                    b.HasOne("TspuWebPortal.Model.InitialDetailRecordData", "InitialDetailRecord")
                        .WithMany("Chassis")
                        .HasForeignKey("InitialDetailRecordId");

                    b.Navigation("DetailChange");

                    b.Navigation("EntityModel");

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialDetailRecordData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.EntityModelData", "EntityModel")
                        .WithMany("InitialDetailRecords")
                        .HasForeignKey("EntityModelId");

                    b.HasOne("TspuWebPortal.Model.InitialDetailTableData", "InitialDetailTable")
                        .WithMany("InitialDetailRecords")
                        .HasForeignKey("InitialDetailTableId");

                    b.HasOne("TspuWebPortal.Model.OperationData", "Operation")
                        .WithMany("InitialDetailRecord")
                        .HasForeignKey("OperationId");

                    b.Navigation("EntityModel");

                    b.Navigation("InitialDetailTable");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialDetailTableData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.FileData", "TableFile")
                        .WithMany("InitialDetailTables")
                        .HasForeignKey("FileId");

                    b.Navigation("TableFile");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialMaterialRecordData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.InitialMaterialTableData", "InitialMaterialTable")
                        .WithMany("InitialMaterialRecords")
                        .HasForeignKey("InitialMaterialTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.OperationData", "Operation")
                        .WithMany("InitialMaterialRecord")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialMaterialTable");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialMaterialTableData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.FileData", "TableFile")
                        .WithMany("InitialMaterialTables")
                        .HasForeignKey("TableFileFileId");

                    b.Navigation("TableFile");
                });

            modelBuilder.Entity("TspuWebPortal.Model.LicenseData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.EntityModelData", "EntityModel")
                        .WithMany("Licenses")
                        .HasForeignKey("EntityModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.InitialDetailRecordData", "InitialDetailRecord")
                        .WithMany("Licenses")
                        .HasForeignKey("InitialDetailRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityModel");

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.LinkData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.CableData", "Cable")
                        .WithMany()
                        .HasForeignKey("CableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.ModuleAData", "ModuleA")
                        .WithOne("Link")
                        .HasForeignKey("TspuWebPortal.Model.LinkData", "ModuleAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.ModuleBData", "ModuleB")
                        .WithOne("Link")
                        .HasForeignKey("TspuWebPortal.Model.LinkData", "ModuleBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cable");

                    b.Navigation("ModuleA");

                    b.Navigation("ModuleB");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleAData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ModuleData", "Module")
                        .WithOne("ModuleA")
                        .HasForeignKey("TspuWebPortal.Model.ModuleAData", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleBData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ModuleData", "Module")
                        .WithOne("ModuleB")
                        .HasForeignKey("TspuWebPortal.Model.ModuleBData", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.CardData", "Card")
                        .WithMany("Modules")
                        .HasForeignKey("CardId");

                    b.HasOne("TspuWebPortal.Model.ChassisData", "Chassis")
                        .WithMany("Modules")
                        .HasForeignKey("ChassisId");

                    b.HasOne("TspuWebPortal.Model.ChangeApplicationData", "DetailChange")
                        .WithMany("Modules")
                        .HasForeignKey("DetailChangeId");

                    b.HasOne("TspuWebPortal.Model.EntityModelData", "EntityModel")
                        .WithMany("Modules")
                        .HasForeignKey("EntityModelId");

                    b.HasOne("TspuWebPortal.Model.InitialDetailRecordData", "InitialDetailRecord")
                        .WithMany("Module")
                        .HasForeignKey("InitialDetailRecordId");

                    b.Navigation("Card");

                    b.Navigation("Chassis");

                    b.Navigation("DetailChange");

                    b.Navigation("EntityModel");

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.OperationData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.UserListData", "UserList")
                        .WithMany("Operations")
                        .HasForeignKey("UserListAccountId");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RackData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.RowData", "Row")
                        .WithMany("Rows")
                        .HasForeignKey("RowId");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCompletionData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.OperationData", "Operation")
                        .WithOne("RequestCompletion")
                        .HasForeignKey("TspuWebPortal.Model.RequestCompletionData", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCreationData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.OperationData", "Operation")
                        .WithOne("RequestCreation")
                        .HasForeignKey("TspuWebPortal.Model.RequestCreationData", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RoomData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.DcData", "DataCenter")
                        .WithMany("Rooms")
                        .HasForeignKey("DataCenterId");

                    b.Navigation("DataCenter");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RowData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.RoomData", "Room")
                        .WithMany("Rows")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ServerLinkData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ServerSlotData", "ServerSlots")
                        .WithMany("ServerLinks")
                        .HasForeignKey("ServerSlotsServerSlotId");

                    b.Navigation("ServerSlots");
                });

            modelBuilder.Entity("TspuWebPortal.Model.UnitData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ChassisData", "Chassis")
                        .WithMany("Units")
                        .HasForeignKey("ChassisId");

                    b.HasOne("TspuWebPortal.Model.RackData", "Rack")
                        .WithMany("Rows")
                        .HasForeignKey("RackId");

                    b.HasOne("TspuWebPortal.Model.ServerSlotData", "ServerSlot")
                        .WithMany("Units")
                        .HasForeignKey("ServerSlotId");

                    b.Navigation("Chassis");

                    b.Navigation("Rack");

                    b.Navigation("ServerSlot");
                });

            modelBuilder.Entity("TspuWebPortal.Model.CardData", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChangeApplicationData", b =>
                {
                    b.Navigation("Cables");

                    b.Navigation("Cards");

                    b.Navigation("Chassis");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChassisData", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Modules");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DcData", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TspuWebPortal.Model.EntityModelData", b =>
                {
                    b.Navigation("Cables");

                    b.Navigation("Cards");

                    b.Navigation("Chassis");

                    b.Navigation("InitialDetailRecords");

                    b.Navigation("Licenses");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("TspuWebPortal.Model.FileData", b =>
                {
                    b.Navigation("InitialDetailTables");

                    b.Navigation("InitialMaterialTables");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialDetailRecordData", b =>
                {
                    b.Navigation("Cables");

                    b.Navigation("Card");

                    b.Navigation("Chassis");

                    b.Navigation("Licenses");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialDetailTableData", b =>
                {
                    b.Navigation("InitialDetailRecords");
                });

            modelBuilder.Entity("TspuWebPortal.Model.InitialMaterialTableData", b =>
                {
                    b.Navigation("InitialMaterialRecords");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleAData", b =>
                {
                    b.Navigation("Link");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleBData", b =>
                {
                    b.Navigation("Link");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleData", b =>
                {
                    b.Navigation("ModuleA");

                    b.Navigation("ModuleB");
                });

            modelBuilder.Entity("TspuWebPortal.Model.OperationData", b =>
                {
                    b.Navigation("InitialDetailRecord");

                    b.Navigation("InitialMaterialRecord");

                    b.Navigation("RequestCompletion");

                    b.Navigation("RequestCreation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RackData", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCompletionData", b =>
                {
                    b.Navigation("ChangeApplication");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCreationData", b =>
                {
                    b.Navigation("ChangeApplication");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RoomData", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RowData", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ServerSlotData", b =>
                {
                    b.Navigation("ServerLinks");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("TspuWebPortal.Model.UserListData", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
