// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TspuWebPortal.ORM;

#nullable disable

namespace TspuWebPortal.Migrations
{
    [DbContext(typeof(TspuDbContext))]
    [Migration("20220720122115_Minor_14")]
    partial class Minor_14
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TspuWebPortal.Model.CableData", b =>
                {
                    b.Property<int>("CableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CableId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("boolean");

                    b.HasKey("CableId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Cables");
                });

            modelBuilder.Entity("TspuWebPortal.Model.CardData", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardId"));

                    b.Property<int>("ChassisId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionInUpperEntity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CardId");

                    b.HasIndex("ChassisId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChangeApplicationData", b =>
                {
                    b.Property<int>("DetailChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetailChangeId"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CompleteChangeDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<int>("JiraApplicationId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestCompletionId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestCreationId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsiblePerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnNewDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnOldDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DetailChangeId");

                    b.HasIndex("RequestCompletionId")
                        .IsUnique();

                    b.HasIndex("RequestCreationId")
                        .IsUnique();

                    b.ToTable("DetailChange");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChassisData", b =>
                {
                    b.Property<int>("ChassisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChassisId"));

                    b.Property<string>("ChassisStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.HasKey("ChassisId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Chassis");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DcData", b =>
                {
                    b.Property<int>("DataCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DataCenterId"));

                    b.Property<string>("DataCenterAddress")
                        .HasColumnType("text");

                    b.Property<string>("DataCenterName")
                        .HasColumnType("text");

                    b.HasKey("DataCenterId");

                    b.ToTable("DataCenters");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailModelData", b =>
                {
                    b.Property<int>("EntityModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityModelId"));

                    b.Property<int?>("ChassisHeightInUnits")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaximalPower")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NominalPower")
                        .HasColumnType("integer");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnDefinitionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EntityModelId");

                    b.ToTable("EntityModel");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailOperationData", b =>
                {
                    b.Property<int>("DetailOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetailOperationId"));

                    b.Property<int>("DetailRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("GlobalOperationId")
                        .HasColumnType("integer");

                    b.Property<string>("OperationSubtype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DetailOperationId");

                    b.HasIndex("DetailRecordId");

                    b.HasIndex("GlobalOperationId")
                        .IsUnique();

                    b.ToTable("DetailOperations");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailRecordData", b =>
                {
                    b.Property<int>("DetailRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetailRecordId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("text");

                    b.Property<int>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<string>("DetailOfficialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DetailOrigin")
                        .HasColumnType("integer");

                    b.Property<int>("InitialDetailTableId")
                        .HasColumnType("integer");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsExcludedFromPrint")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSplittable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccessfullyUploaded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleInExcel")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsiblePerson")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpecDetailId")
                        .HasColumnType("integer");

                    b.HasKey("DetailRecordId");

                    b.HasIndex("InitialDetailTableId");

                    b.HasIndex("SpecDetailId");

                    b.ToTable("DetailRecords");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailTableData", b =>
                {
                    b.Property<int>("InitialDetailTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InitialDetailTableId"));

                    b.Property<int?>("FileId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("RegisterDate")
                        .HasColumnType("date");

                    b.HasKey("InitialDetailTableId");

                    b.HasIndex("FileId");

                    b.ToTable("DetailTables");
                });

            modelBuilder.Entity("TspuWebPortal.Model.FileData", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileId"));

                    b.Property<string>("FileCategory")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAppliedToTable")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastChangeDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("UploadDate")
                        .HasColumnType("date");

                    b.HasKey("FileId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("TspuWebPortal.Model.LicenseData", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LicenseId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<int>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LicenseId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("TspuWebPortal.Model.LinkData", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkId"));

                    b.Property<int>("CableId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<int>("ModuleAId")
                        .HasColumnType("integer");

                    b.Property<int>("ModuleBId")
                        .HasColumnType("integer");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.Property<string>("RdLinkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualPortA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualPortB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LinkId");

                    b.HasIndex("CableId");

                    b.HasIndex("ModuleAId")
                        .IsUnique();

                    b.HasIndex("ModuleBId")
                        .IsUnique();

                    b.ToTable("Links");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialModelData", b =>
                {
                    b.Property<int>("MaterialEntityModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaterialEntityModelId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaterialEntityModelId");

                    b.ToTable("MaterialEntityModels");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialOperationData", b =>
                {
                    b.Property<int>("MaterialOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaterialOperationId"));

                    b.Property<int>("GlobalOperationId")
                        .HasColumnType("integer");

                    b.Property<string>("OperationSubtype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StorageItemId")
                        .HasColumnType("integer");

                    b.HasKey("MaterialOperationId");

                    b.HasIndex("GlobalOperationId")
                        .IsUnique();

                    b.HasIndex("StorageItemId");

                    b.ToTable("MaterialOperations");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialStorageData", b =>
                {
                    b.Property<int>("StorageItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StorageItemId"));

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("DataCenterId")
                        .HasColumnType("integer");

                    b.Property<int>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<int>("InstalledQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialEntityModelId")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialSpecificationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TakenQuantity")
                        .HasColumnType("integer");

                    b.HasKey("StorageItemId");

                    b.HasIndex("DataCenterId");

                    b.HasIndex("MaterialEntityModelId");

                    b.ToTable("StorageRecords");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialTableData", b =>
                {
                    b.Property<int>("InitialMaterialTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InitialMaterialTableId"));

                    b.Property<int?>("FileId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("RegisterDate")
                        .HasColumnType("date");

                    b.HasKey("InitialMaterialTableId");

                    b.HasIndex("FileId");

                    b.ToTable("MaterialTable");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialTableStorageLink", b =>
                {
                    b.Property<int>("InitialMaterialTableId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialStorageItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialOperationDataMaterialOperationId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialStorageDataStorageItemId")
                        .HasColumnType("integer");

                    b.HasKey("InitialMaterialTableId", "MaterialStorageItemId");

                    b.HasIndex("MaterialOperationDataMaterialOperationId");

                    b.HasIndex("MaterialStorageDataStorageItemId");

                    b.HasIndex("MaterialStorageItemId");

                    b.ToTable("MaterialTableStorageLink");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleAData", b =>
                {
                    b.Property<int>("ModuleAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleAId"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.HasKey("ModuleAId");

                    b.HasIndex("ModuleId")
                        .IsUnique();

                    b.ToTable("ModulesA");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleBData", b =>
                {
                    b.Property<int>("ModuleBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleBId"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.HasKey("ModuleBId");

                    b.HasIndex("ModuleId")
                        .IsUnique();

                    b.ToTable("ModulesB");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleData", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<int?>("CardId")
                        .HasColumnType("integer");

                    b.Property<int?>("ChassisId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HydraEndNumber")
                        .HasColumnType("integer");

                    b.Property<int>("InitialDetailRecordId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionInUpperEntity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ModuleId");

                    b.HasIndex("CardId");

                    b.HasIndex("ChassisId");

                    b.HasIndex("InitialDetailRecordId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("TspuWebPortal.Model.OperationSummaryData", b =>
                {
                    b.Property<int>("GlobalOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GlobalOperationId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("OperationDate")
                        .HasColumnType("date");

                    b.Property<string>("OperationType")
                        .HasColumnType("text");

                    b.Property<int?>("UserListAccountId")
                        .HasColumnType("integer");

                    b.HasKey("GlobalOperationId");

                    b.HasIndex("UserListAccountId");

                    b.ToTable("OperationSummary");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RackData", b =>
                {
                    b.Property<int>("RackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RackId"));

                    b.Property<int?>("FreeServerSlotsQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("InstallationYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<int?>("RackHeight")
                        .HasColumnType("integer");

                    b.Property<string>("RackNameAsbi")
                        .HasColumnType("text");

                    b.Property<string>("RackNameDataCenter")
                        .HasColumnType("text");

                    b.Property<string>("RackType")
                        .HasColumnType("text");

                    b.Property<int?>("RowId")
                        .HasColumnType("integer");

                    b.HasKey("RackId");

                    b.HasIndex("RowId");

                    b.ToTable("Racks");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCompletionData", b =>
                {
                    b.Property<int>("RequestCompletionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestCompletionId"));

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.HasKey("RequestCompletionId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("CompletionRequests");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCreationData", b =>
                {
                    b.Property<int>("RequestCreationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestCreationId"));

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.HasKey("RequestCreationId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("CreationRequests");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RoomData", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("DataCenterId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomCoordinates")
                        .HasColumnType("text");

                    b.Property<string>("RoomName")
                        .HasColumnType("text");

                    b.HasKey("RoomId");

                    b.HasIndex("DataCenterId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RowData", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("RowNameAsbi")
                        .HasColumnType("text");

                    b.Property<string>("RowNameDataCenter")
                        .HasColumnType("text");

                    b.HasKey("RowId");

                    b.HasIndex("RoomId");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ServerLinkData", b =>
                {
                    b.Property<int>("ServerLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerLinkId"));

                    b.Property<int>("ServerSlotId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServerSlotsServerSlotId")
                        .HasColumnType("integer");

                    b.Property<int>("ServerTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ServerLinkId");

                    b.HasIndex("ServerSlotsServerSlotId");

                    b.ToTable("ServerLinks");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ServerSlotData", b =>
                {
                    b.Property<int>("ServerSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerSlotId"));

                    b.Property<string>("SlotIndex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("ServerSlotId");

                    b.ToTable("ServerSlots");
                });

            modelBuilder.Entity("TspuWebPortal.Model.SiteData", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("FederalDistrict")
                        .HasColumnType("text");

                    b.Property<string>("IsInProject")
                        .HasColumnType("text");

                    b.Property<string>("Links")
                        .HasColumnType("text");

                    b.Property<string>("MaintainanceStatus")
                        .HasColumnType("text");

                    b.Property<string>("Oper")
                        .HasColumnType("text");

                    b.Property<string>("PipelineStage")
                        .HasColumnType("text");

                    b.Property<int?>("RegionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SiteType")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("TspuWebPortal.Model.SpecDetailData", b =>
                {
                    b.Property<int>("SpecDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecDetailId"));

                    b.Property<int>("DeliveryYear")
                        .HasColumnType("integer");

                    b.Property<int>("EntityModelId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecItemFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecItemShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpecDetailId");

                    b.HasIndex("EntityModelId");

                    b.ToTable("SpecificationRecords");
                });

            modelBuilder.Entity("TspuWebPortal.Model.UnitData", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<int?>("ChassisId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsChassisLowerUnit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFront")
                        .HasColumnType("boolean");

                    b.Property<int>("RackId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServerSlotId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitInRack")
                        .HasColumnType("integer");

                    b.HasKey("UnitId");

                    b.HasIndex("ChassisId");

                    b.HasIndex("RackId");

                    b.HasIndex("ServerSlotId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("TspuWebPortal.Model.UserListData", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("TspuWebPortal.Model.CableData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.DetailRecordData", "InitialDetailRecord")
                        .WithMany("Cables")
                        .HasForeignKey("InitialDetailRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.CardData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ChassisData", "Chassis")
                        .WithMany("Cards")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.DetailRecordData", "InitialDetailRecord")
                        .WithMany("Card")
                        .HasForeignKey("InitialDetailRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chassis");

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChangeApplicationData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.RequestCompletionData", "RequestCompletion")
                        .WithOne("ChangeApplication")
                        .HasForeignKey("TspuWebPortal.Model.ChangeApplicationData", "RequestCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.RequestCreationData", "RequestCreation")
                        .WithOne("ChangeApplication")
                        .HasForeignKey("TspuWebPortal.Model.ChangeApplicationData", "RequestCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestCompletion");

                    b.Navigation("RequestCreation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChassisData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.DetailRecordData", "InitialDetailRecord")
                        .WithMany("Chassis")
                        .HasForeignKey("InitialDetailRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailOperationData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.DetailRecordData", "DetailRecord")
                        .WithMany("DetailOperations")
                        .HasForeignKey("DetailRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.OperationSummaryData", "GlobalOperation")
                        .WithOne("DetailOperation")
                        .HasForeignKey("TspuWebPortal.Model.DetailOperationData", "GlobalOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailRecord");

                    b.Navigation("GlobalOperation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailRecordData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.DetailTableData", "InitialDetailTable")
                        .WithMany("InitialDetailRecords")
                        .HasForeignKey("InitialDetailTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.SpecDetailData", "SpecDetail")
                        .WithMany("InitialDetailRecords")
                        .HasForeignKey("SpecDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialDetailTable");

                    b.Navigation("SpecDetail");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailTableData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.FileData", "TableFile")
                        .WithMany("InitialDetailTables")
                        .HasForeignKey("FileId");

                    b.Navigation("TableFile");
                });

            modelBuilder.Entity("TspuWebPortal.Model.LicenseData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.DetailRecordData", "InitialDetailRecord")
                        .WithMany("Licenses")
                        .HasForeignKey("InitialDetailRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.LinkData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.CableData", "Cable")
                        .WithMany()
                        .HasForeignKey("CableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.ModuleAData", "ModuleA")
                        .WithOne("Link")
                        .HasForeignKey("TspuWebPortal.Model.LinkData", "ModuleAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.ModuleBData", "ModuleB")
                        .WithOne("Link")
                        .HasForeignKey("TspuWebPortal.Model.LinkData", "ModuleBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cable");

                    b.Navigation("ModuleA");

                    b.Navigation("ModuleB");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialOperationData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.OperationSummaryData", "GlobalOperation")
                        .WithOne("MaterialOperation")
                        .HasForeignKey("TspuWebPortal.Model.MaterialOperationData", "GlobalOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.MaterialStorageData", "MaterialModel")
                        .WithMany("MaterialOperations")
                        .HasForeignKey("StorageItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalOperation");

                    b.Navigation("MaterialModel");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialStorageData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.DcData", "DataCenter")
                        .WithMany("MaterialStorageItems")
                        .HasForeignKey("DataCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.MaterialModelData", "MaterialModel")
                        .WithMany("MaterialStorageItems")
                        .HasForeignKey("MaterialEntityModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataCenter");

                    b.Navigation("MaterialModel");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialTableData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.FileData", "TableFile")
                        .WithMany("InitialMaterialTables")
                        .HasForeignKey("FileId");

                    b.Navigation("TableFile");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialTableStorageLink", b =>
                {
                    b.HasOne("TspuWebPortal.Model.MaterialOperationData", null)
                        .WithMany("TableStorageLinks")
                        .HasForeignKey("MaterialOperationDataMaterialOperationId");

                    b.HasOne("TspuWebPortal.Model.MaterialStorageData", "MaterialStorageData")
                        .WithMany("TableStorageLinks")
                        .HasForeignKey("MaterialStorageDataStorageItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.MaterialTableData", "InitialMaterialTableData")
                        .WithMany("TableStorageLinks")
                        .HasForeignKey("MaterialStorageItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialMaterialTableData");

                    b.Navigation("MaterialStorageData");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleAData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ModuleData", "Module")
                        .WithOne("ModuleA")
                        .HasForeignKey("TspuWebPortal.Model.ModuleAData", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleBData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ModuleData", "Module")
                        .WithOne("ModuleB")
                        .HasForeignKey("TspuWebPortal.Model.ModuleBData", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.CardData", "Card")
                        .WithMany("Modules")
                        .HasForeignKey("CardId");

                    b.HasOne("TspuWebPortal.Model.ChassisData", "Chassis")
                        .WithMany("Modules")
                        .HasForeignKey("ChassisId");

                    b.HasOne("TspuWebPortal.Model.DetailRecordData", "InitialDetailRecord")
                        .WithMany("Module")
                        .HasForeignKey("InitialDetailRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Chassis");

                    b.Navigation("InitialDetailRecord");
                });

            modelBuilder.Entity("TspuWebPortal.Model.OperationSummaryData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.UserListData", "UserList")
                        .WithMany("Operations")
                        .HasForeignKey("UserListAccountId");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RackData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.RowData", "Row")
                        .WithMany("Racks")
                        .HasForeignKey("RowId");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCompletionData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.OperationSummaryData", "Operation")
                        .WithOne("RequestCompletion")
                        .HasForeignKey("TspuWebPortal.Model.RequestCompletionData", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCreationData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.OperationSummaryData", "Operation")
                        .WithOne("RequestCreation")
                        .HasForeignKey("TspuWebPortal.Model.RequestCreationData", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RoomData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.DcData", "DataCenter")
                        .WithMany("Rooms")
                        .HasForeignKey("DataCenterId");

                    b.Navigation("DataCenter");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RowData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.RoomData", "Room")
                        .WithMany("Rows")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ServerLinkData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ServerSlotData", "ServerSlots")
                        .WithMany("ServerLinks")
                        .HasForeignKey("ServerSlotsServerSlotId");

                    b.Navigation("ServerSlots");
                });

            modelBuilder.Entity("TspuWebPortal.Model.SpecDetailData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.DetailModelData", "EntityModel")
                        .WithMany("SpecificationRecords")
                        .HasForeignKey("EntityModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityModel");
                });

            modelBuilder.Entity("TspuWebPortal.Model.UnitData", b =>
                {
                    b.HasOne("TspuWebPortal.Model.ChassisData", "Chassis")
                        .WithMany("Units")
                        .HasForeignKey("ChassisId");

                    b.HasOne("TspuWebPortal.Model.RackData", "Rack")
                        .WithMany("Units")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TspuWebPortal.Model.ServerSlotData", "ServerSlot")
                        .WithMany("Units")
                        .HasForeignKey("ServerSlotId");

                    b.Navigation("Chassis");

                    b.Navigation("Rack");

                    b.Navigation("ServerSlot");
                });

            modelBuilder.Entity("TspuWebPortal.Model.CardData", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ChassisData", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Modules");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DcData", b =>
                {
                    b.Navigation("MaterialStorageItems");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailModelData", b =>
                {
                    b.Navigation("SpecificationRecords");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailRecordData", b =>
                {
                    b.Navigation("Cables");

                    b.Navigation("Card");

                    b.Navigation("Chassis");

                    b.Navigation("DetailOperations");

                    b.Navigation("Licenses");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TspuWebPortal.Model.DetailTableData", b =>
                {
                    b.Navigation("InitialDetailRecords");
                });

            modelBuilder.Entity("TspuWebPortal.Model.FileData", b =>
                {
                    b.Navigation("InitialDetailTables");

                    b.Navigation("InitialMaterialTables");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialModelData", b =>
                {
                    b.Navigation("MaterialStorageItems");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialOperationData", b =>
                {
                    b.Navigation("TableStorageLinks");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialStorageData", b =>
                {
                    b.Navigation("MaterialOperations");

                    b.Navigation("TableStorageLinks");
                });

            modelBuilder.Entity("TspuWebPortal.Model.MaterialTableData", b =>
                {
                    b.Navigation("TableStorageLinks");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleAData", b =>
                {
                    b.Navigation("Link");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleBData", b =>
                {
                    b.Navigation("Link");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ModuleData", b =>
                {
                    b.Navigation("ModuleA");

                    b.Navigation("ModuleB");
                });

            modelBuilder.Entity("TspuWebPortal.Model.OperationSummaryData", b =>
                {
                    b.Navigation("DetailOperation");

                    b.Navigation("MaterialOperation");

                    b.Navigation("RequestCompletion");

                    b.Navigation("RequestCreation");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RackData", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCompletionData", b =>
                {
                    b.Navigation("ChangeApplication");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RequestCreationData", b =>
                {
                    b.Navigation("ChangeApplication");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RoomData", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("TspuWebPortal.Model.RowData", b =>
                {
                    b.Navigation("Racks");
                });

            modelBuilder.Entity("TspuWebPortal.Model.ServerSlotData", b =>
                {
                    b.Navigation("ServerLinks");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("TspuWebPortal.Model.SpecDetailData", b =>
                {
                    b.Navigation("InitialDetailRecords");
                });

            modelBuilder.Entity("TspuWebPortal.Model.UserListData", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
